import { defineConfig } from 'tsup';

export default defineConfig({
  entry: ['src/index.ts'],
  format: ['cjs', 'esm'],
  dts: true,
  splitting: false,
  sourcemap: true,
  clean: true,
  external: [
    'react',
    'react-dom',
    'react/jsx-runtime',
    '@radix-ui/react-accordion',
    '@radix-ui/react-alert-dialog',
    '@radix-ui/react-avatar',
    '@radix-ui/react-checkbox',
    '@radix-ui/react-collapsible',
    '@radix-ui/react-dialog',
    '@radix-ui/react-dropdown-menu',
    '@radix-ui/react-icons',
    '@radix-ui/react-label',
    '@radix-ui/react-popover',
    '@radix-ui/react-progress',
    '@radix-ui/react-radio-group',
    '@radix-ui/react-scroll-area',
    '@radix-ui/react-select',
    '@radix-ui/react-separator',
    '@radix-ui/react-slider',
    '@radix-ui/react-slot',
    '@radix-ui/react-switch',
    '@radix-ui/react-tabs',
    '@radix-ui/react-toast',
    '@radix-ui/react-toggle',
    '@radix-ui/react-toggle-group',
    '@radix-ui/react-tooltip',
    'lucide-react',
    'clsx',
    'tailwind-merge',
    'class-variance-authority',
    'framer-motion',
    'react-hook-form',
    'zod',
    '@hookform/resolvers',
    'date-fns',
    'react-day-picker',
    'react-dropzone',
    'react-colorful',
    'input-otp',
    'sonner',
    'recharts',
    'lexical',
    '@lexical/react',
    '@lexical/rich-text',
    '@lexical/utils',
    'uuid',
    'lodash-es',
    'cmdk',
    'embla-carousel-react',
    'qrcode.react',
    'katex',
    '@excalidraw/excalidraw',
    '@dnd-kit/core',
    '@dnd-kit/sortable',
    '@dnd-kit/utilities',
    'sortablejs',
    'react-sortablejs',
    'browser-fs-access'
  ],
  treeshake: true,
});

