import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import '@/styles/globals.css';
import { SidebarProvider, SidebarTrigger } from '@/components/sidebar/sidebar';
import { AppSidebar } from '@/components/layouts/app-sidebar';
import Navbar from '@/components/layouts/navbar';
import { ThemeProvider } from '@/providers/theme-provider';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-background`}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <SidebarProvider>
            <div className="flex h-screen w-full">
              {/* Sidebar */}
              <AppSidebar className="h-full border-r bg-red-900 transition-all duration-300" />

              {/* Main Content */}
              <div className="flex flex-col flex-1 w-full min-w-0">
                {/* Navbar */}
                <header className="border-b px-4 py-2 flex items-center">
                  <SidebarTrigger />
                  <Navbar className="flex-1" />
                </header>

                {/* Page Content */}
                <main className="flex-1 w-full p-8">{children}</main>
              </div>
            </div>
          </SidebarProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
